Q1. What is a Python library? Why we use Python libraries?

Sol 1.  
- A Python library is a pre written code consisting of various functions which can be used for performing specific tasks.  
- We use these python libraries so that we can perform required task without having to write the whole basic code
- We can simply import the library, call the function to perform the task.
- These libraries improve code resuability and are simple to use

Q2. What is the difference between Numpy array and List?

Sol 2 .

| NumPy Array                                  | Python List                           |
|----------------------------------------------|---------------------------------------|
| Numpy stands for numerical python, these numpy arrays are specifically made to perform numeric calculations more efficiently. | Lists are general-purpose data structures. |
| These are homogeneous in nature, meaning all the elements have to have the same data type. | Lists are heterogeneous in nature, meaning it can store multiple or different data types of elements. |
| They are more memory efficient than regular lists. | These have overheads and are less memory efficient. |
| In numpy array we can reshape a matrix.     | Once a list is declared we cannot reshape it. |
| We can do broadcasting in numpy array.      | We cannot do broadcasting on lists.  |




<!-- > Numpy array
- Numpy stands for numerical python, these numpy array are specifically made to perform numeric calculations more efficently.  
- These are homogenous in nature, meaning all the elements have to have same data type.
- They are more memory effecient than regular lists.
- In numpy array we can reshape a matrix.
- We can do broadcasting in numpy array.

> Python List
- Lists are general purpose data structure.  
- Lists are hetrogenous in nature, meaning it can store multiple or different data types of elements.  
- These have overheads and are less memory efficent.
- Once a list is decalred we cannot reshape it.
- We cannot reshape a list.
- We cannot do broadcasting on lists.  -->

### Q3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [1]:
import numpy as np
x = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])

In [2]:
x.shape

(3, 4)

In [3]:
x.size

12

In [4]:
x.ndim

2

### Q4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [5]:
y = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
y[0]

array([1, 2, 3, 4])

### Q5. How do you access the element at the third row and fourth column from the given numpy array?

In [6]:
z = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
z[2][3]

12

### Q6. Write code to extract all odd - indexed elements from the given numpy array?

In [7]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
a[:, 1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

### Q7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [8]:
np.random.rand(3,3)

array([[0.70389719, 0.44612929, 0.05557972],
       [0.1538992 , 0.0312991 , 0.83455243],
       [0.33492804, 0.28181345, 0.10689918]])

### Q8. # Describe the difference between np.random.rand and np.random.randn?

In [9]:
np.random.rand(3,3)
# It generatess random numbers between 0 (inclusive) and 1 (exclusive).

array([[0.14761878, 0.76329884, 0.11311003],
       [0.9701767 , 0.49625688, 0.46375717],
       [0.59207736, 0.91564409, 0.679618  ]])

In [10]:
np.random.randn(3,3)
# It generates random numbers that have a normal distribution, a mean of 0 and a standard deviation of 1.

array([[-0.22429336, -2.03465565, -0.60653025],
       [ 0.53195211, -1.43189053, -0.57014095],
       [-0.50591333, -2.00646073,  0.09094205]])

### Q9. Write code to increase the dimension of the following array?

In [11]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [12]:
np.expand_dims(b, axis = 0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

### Q10. How to transpose the following array in NumPy?

In [13]:
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [14]:
c.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### Q11. Consider the following matrix:
#### Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
#### Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python

- Index wise  multiplication
- Matix multiplication
- Add both the matrics
- Subtact matix B from A
- Diide Matix B by A

In [15]:
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
b2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [16]:
a2 * b2
# Index wise multiplication

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [17]:
a2 @ b2.T
# Matix multiplication

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [18]:
a2 + b2
# Add both the matrics

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [19]:
a2 - b2
# Subtact matix B from A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [20]:
b2 / a2
# Diide Matix B by A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
# byteswap() function
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

### Q12. Which function in Numpy can be used to swap the byte order of an array?

In [22]:
c.byteswap()
# we can use byteswap() function

array([[ 72057594037927936, 144115188075855872, 216172782113783808,
        288230376151711744],
       [360287970189639680, 432345564227567616, 504403158265495552,
        576460752303423488],
       [648518346341351424, 720575940379279360, 792633534417207296,
        864691128455135232]])

### Q13. What is the significance of the np.linalg.inv function?

In [23]:
d = np.array([[2, 3], [4, 5]])
np.linalg.inv(d)
# calculates the inverse of a given array

array([[-2.5,  1.5],
       [ 2. , -1. ]])

### Q14. What does the np.reshape function do, and how is it used?

In [24]:
np.reshape(d, (1,4))
# it reshapes the given array into desired diemnsion with the same elements

array([[2, 3, 4, 5]])

### Q15. What is broadcasting in Numpy?

In [25]:
# doing opearation to the whole array
# to perform element-wise operations on arrays of different shapes

e = np.array([[1, 2, 3], [4, 5, 6]])
f = np.array([10, 20, 30])

e + f


array([[11, 22, 33],
       [14, 25, 36]])